server:
  port: ${port:9090}
  servlet:
    context-path: / #defeault 값은 /이다.
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://b540342f410e02:aa5453df@us-cdbr-east-04.cleardb.com/heroku_a491c27c4ef8256?reconnect=true
    username: b540342f410e02
    password: aa5453df
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #create : 프로젝트를 실행할 때마다 create해준다. (최초만 create로 해주어야 하고, 후에는 update로 변경해야 한다.)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity(테이블)을 만들때 변수명 그대로 필드에 넣어주는 것이다.
      use-new-id-generator-mappings: false # false : jpa가 사용하는 기본 넘버링 전략을 따라가지 않는다. 
    #show-sql: true #true일시 콘솔창에 쿼리를 보여준다.
    properties:
      hibernate.format_sql: true #true일시 콘솔창에 쿼리를 보여주는 것이 자동으로 정렬되서 나옴(기본값은 한줄로 나온다.)

  jackson:
    serialization:
      fail-on-empty-beans: false
 
cos:
  key: cos1234